On RHEL 6.9 (minimal installation) step 'Installing DB2 10.5' fails with statement below
A minor error occurred while installing "DB2 Server Edition " on this
computer. Some features may not function correctly.

For more information see the DB2 installation log at "/tmp/db2setup.log".

=== /tmp/db2setup.log contains following error
ERROR: /home/db2inst1/sqllib/adm/db2start: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory
ERROR: An error occurred while trying to start the "db2inst1" instance. The
return code is "127" and the SQL Message is:   "PROCESS_ERROR"

ERROR: An error occurred while configuring the instance "db2inst1".
======
The missing file is provided by package 'numactl' in RHEL 6.